2022/04/07 06:56:03 [error] 33#33: *12 open() "/var/www/html/test/favicon.ico" failed (2: No such file or directory), client: 192.168.80.1, server: shf.test.org, request: "GET /favicon.ico HTTP/1.1", host: "shf.test.org", referrer: "http://shf.test.org/"
2022/04/07 06:56:21 [error] 33#33: *13 open() "/var/www/html/test/favicon.ico" failed (2: No such file or directory), client: 192.168.80.1, server: shf.test.org, request: "GET /favicon.ico HTTP/1.1", host: "shf.test.org", referrer: "http://shf.test.org/"
2022/04/07 08:25:05 [error] 33#33: *2 open() "/var/www/html/test/favicon.ico" failed (2: No such file or directory), client: 192.168.208.1, server: shf.test.org, request: "GET /favicon.ico HTTP/1.1", host: "shf.test.org", referrer: "http://shf.test.org/"
2022/04/07 11:47:45 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.240.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.3:9000", host: "shf.test.org"
2022/04/07 11:47:46 [error] 33#33: *1 open() "/var/www/html/test/favicon.ico" failed (2: No such file or directory), client: 192.168.240.1, server: shf.test.org, request: "GET /favicon.ico HTTP/1.1", host: "shf.test.org", referrer: "http://shf.test.org/"
2022/04/07 12:02:13 [error] 34#34: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.22.0.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "shf.test.org"
2022/04/07 12:50:45 [error] 35#35: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.23.0.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9000", host: "shf.test.org"
2022/04/08 02:50:29 [error] 35#35: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.25.0.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.3:9000", host: "shf.test.org"
2022/04/08 02:50:29 [error] 35#35: *1 open() "/var/www/html/test/favicon.ico" failed (2: No such file or directory), client: 172.25.0.1, server: shf.test.org, request: "GET /favicon.ico HTTP/1.1", host: "shf.test.org", referrer: "http://shf.test.org/"
2022/04/08 07:47:19 [error] 32#32: *1 open() "/var/www/html/test/favicon.ico" failed (2: No such file or directory), client: 172.20.0.1, server: shf.test.org, request: "GET /favicon.ico HTTP/1.1", host: "shf.test.org", referrer: "http://shf.test.org/"
2022/04/08 07:47:20 [error] 32#32: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "shf.test.org"
2022/04/11 06:40:27 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.30.0.1:9005 (from REMOTE_ADDR HTTP header), host.docker.internal:9005 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.30.0.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.2:9000", host: "shf.test.org"
2022/04/11 06:40:31 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.30.0.1:9005 (from REMOTE_ADDR HTTP header), host.docker.internal:9005 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.30.0.1, server: shf.test.org, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.2:9000", host: "shf.test.org"
